import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync } from 'node:crypto';
import { fixture } from './helpers.mjs';
import { stableStringify } from '../src/core/model.js';
import { routeStage } from '../src/core/routing.js';
import { sha256, projectSHA256, createReviewBundle, verifyReviewBundle } from '../src/core/evidence.js';
import { signReview, verifySignedReview } from '../scripts/signing.mjs';
const keys=generateKeyPairSync('ed25519'),privatePEM=keys.privateKey.export({type:'pkcs8',format:'pem'}),publicPEM=keys.publicKey.export({type:'spki',format:'pem'});
test('SHA-256 uses known standard vector',async()=>assert.equal(await sha256('abc'),'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'));
test('canonical hashes ignore object-key order, not values',async()=>{assert.equal(await sha256({a:1,b:2}),await sha256({b:2,a:1}));assert.notEqual(await sha256({a:1}),await sha256({a:2}));});
test('review bundle is reproducible without wall-clock metadata',async()=>{const p=fixture();assert.deepEqual(await createReviewBundle(p),await createReviewBundle(p));});
test('valid bundle independently reruns planning rules',async()=>{const r=await verifyReviewBundle(await createReviewBundle(fixture()));assert.equal(r.valid,true);assert.equal(r.planningPass,true);assert.equal(r.routingPass,null);});
test('hard-rule-failing design is valid evidence, not a passing design',async()=>{const p=fixture();p.ports[1].net='WRONG';const r=await verifyReviewBundle(await createReviewBundle(p));assert.equal(r.valid,true);assert.equal(r.planningPass,false);});
test('valid routing witness is included and reverified',async()=>{const p=fixture(),routing=routeStage(p,'pad','ball',{pitch:10});const r=await verifyReviewBundle(await createReviewBundle(p,{routing}));assert.equal(r.valid,true);assert.equal(r.routingPass,true);});
test('partial route cannot be promoted into an approved bundle',async()=>{const p=fixture(),routing=routeStage(p,'pad','ball',{pitch:10,maxExpansions:1});await assert.rejects(()=>createReviewBundle(p,{routing}),/invalid routing/);});
test('stale route cannot be bundled after a design change',async()=>{const p=fixture(),routing=routeStage(p,'pad','ball',{pitch:10});p.ports[0].x=10;await assert.rejects(()=>createReviewBundle(p,{routing}));});
test('expected project SHA catches replay of an otherwise valid old bundle',async()=>{const p=fixture(),b=await createReviewBundle(p);p.ports[0].x=10;const r=await verifyReviewBundle(b,{expectedProjectSHA256:await projectSHA256(p)});assert.equal(r.valid,false);assert.equal(r.planningPass,false);});
for(const part of ['project','validation','routing','routingVerification'])test(`payload tampering detected: ${part}`,async()=>{const b=await createReviewBundle(fixture());b.payload[part]={fabricated:true};assert.equal((await verifyReviewBundle(b)).valid,false);});
test('manifest pass-flag tampering detected',async()=>{const p=fixture();p.ports[1].net='WRONG';const b=await createReviewBundle(p);b.manifest.planningPass=true;b.manifestSHA256=await sha256(b.manifest);assert.equal((await verifyReviewBundle(b)).valid,false);});
test('rehashing fabricated stored validation does not bypass independent rerun',async()=>{const b=await createReviewBundle(fixture());b.payload.validation.metrics.totalLength=0;b.manifest.digests.validation=await sha256(b.payload.validation);b.manifestSHA256=await sha256(b.manifest);assert.equal((await verifyReviewBundle(b)).valid,false);});
test('unknown engine version cannot silently reuse a previous check',async()=>{const b=await createReviewBundle(fixture());b.manifest.engineVersion='9.9.9';assert.equal((await verifyReviewBundle(b)).valid,false);});
test('unexpected payload entries rejected',async()=>{const b=await createReviewBundle(fixture());b.payload.extra={};assert.equal((await verifyReviewBundle(b)).valid,false);});
test('missing digest rejected',async()=>{const b=await createReviewBundle(fixture());delete b.manifest.digests.validation;assert.equal((await verifyReviewBundle(b)).valid,false);});
test('valid Ed25519 signature authenticates against external trusted key',async()=>{const b=await signReview(await createReviewBundle(fixture()),privatePEM);const r=await verifySignedReview(b,publicPEM);assert.equal(r.valid,true);assert.equal(r.authenticated,true);assert.equal(r.planningPass,true);});
test('wrong trusted key cannot be replaced with an embedded key',async()=>{const b=await signReview(await createReviewBundle(fixture()),privatePEM),other=generateKeyPairSync('ed25519');b.signature.publicKey=publicPEM;const r=await verifySignedReview(b,other.publicKey.export({type:'spki',format:'pem'}));assert.equal(r.authenticated,false);assert.equal(r.valid,false);});
test('a signed old design still fails expected-project freshness',async()=>{const p=fixture(),b=await signReview(await createReviewBundle(p),privatePEM);p.name='Changed';const r=await verifySignedReview(b,publicPEM,{expectedProjectSHA256:await projectSHA256(p)});assert.equal(r.valid,false);assert.equal(r.planningPass,false);});
test('replacing payloads and every unkeyed hash cannot forge a signature',async()=>{const b=await signReview(await createReviewBundle(fixture()),privatePEM),p=fixture();p.name='Substituted project';const forged=await createReviewBundle(p);forged.signature=b.signature;assert.equal((await verifySignedReview(forged,publicPEM)).authenticated,false);});
test('signature body tampering is rejected',async()=>{const b=await signReview(await createReviewBundle(fixture()),privatePEM);b.signature.value='A'.repeat(86)+'==';assert.equal((await verifySignedReview(b,publicPEM)).valid,false);});
test('malformed signature is rejected',async()=>{const b=await signReview(await createReviewBundle(fixture()),privatePEM);b.signature.value='no';assert.equal((await verifySignedReview(b,publicPEM)).valid,false);});
test('missing signature cannot be called authenticated',async()=>assert.equal((await verifySignedReview(await createReviewBundle(fixture()),publicPEM)).authenticated,false));
test('signer refuses a hard-rule-failing project',async()=>{const p=fixture();p.ports[1].net='OTHER';await assert.rejects(()=>createReviewBundle(p).then(b=>signReview(b,privatePEM)),/hard-rule/);});
test('signer refuses corrupted bundle',async()=>{const b=await createReviewBundle(fixture());b.manifestSHA256='bad';await assert.rejects(()=>signReview(b,privatePEM));});
test('non-Ed25519 signing key rejected',async()=>{const ec=generateKeyPairSync('ec',{namedCurve:'prime256v1'});await assert.rejects(()=>createReviewBundle(fixture()).then(b=>signReview(b,ec.privateKey.export({type:'pkcs8',format:'pem'}))),/Ed25519/);});
test('canonical signature payload is independent of manifest property insertion order',async()=>{const b=await signReview(await createReviewBundle(fixture()),privatePEM);b.manifest=Object.fromEntries(Object.entries(b.manifest).reverse());assert.equal((await verifySignedReview(b,publicPEM)).authenticated,true);});
for (const malformed of [true,false]) test(`signature failure clears routing pass flags (${malformed?'malformed':'wrong'} key)`,async()=>{
  const p=fixture(),routing=routeStage(p,'pad','ball',{pitch:10}),b=await signReview(await createReviewBundle(p,{routing}),privatePEM);
  const key=malformed?'not a PEM':generateKeyPairSync('ed25519').publicKey.export({type:'spki',format:'pem'});
  const checked=await verifySignedReview(b,key);assert.equal(checked.valid,false);assert.equal(checked.authenticated,false);assert.equal(checked.planningPass,false);assert.equal(checked.routingPass,false);
});
