import test from 'node:test';import assert from 'node:assert/strict';import {parseCSV,importPortsCSV,importConnectionsCSV,importLEF,generateArray,rowLabel,importJSON} from '../src/core/importers.js';import {exportPortsCSV,exportConnectionsCSV} from '../src/core/exporters.js';import {fixture} from './helpers.mjs';
test('CSV handles BOM, CRLF, embedded comma, quotes, and newline',()=>{const r=parseCSV('\ufeffid,label\r\na,"two, words"\r\nb,"say ""yes""\nnext"\r\n');assert.equal(r[0].label,'two, words');assert.equal(r[1].label,'say "yes"\nnext');});
for(const text of ['a,a\n1,2','a,b\n1','a,b\n1,2,3','a\n"unterminated','a\nb"c','a\n"b"x'])test(`malformed CSV rejected: ${JSON.stringify(text)}`,()=>assert.throws(()=>parseCSV(text)));
test('unit conversion mm to um',()=>assert.equal(importPortsCSV('id,x,y\np,1.25,2',{units:'mm'}).ports[0].x,1250));
test('unit conversion nm to um',()=>assert.equal(importPortsCSV('id,x,y,units\np,1250,2000,nm').ports[0].x,1.25));
test('missing numeric coordinates rejected',()=>assert.throws(()=>importPortsCSV('id,x,y\np,,2'),/finite/));
test('unknown CSV columns rejected',()=>assert.throws(()=>importPortsCSV('id,x,y,voltagedomain\np,1,2,V1'),/Unknown/));
test('duplicate imported IDs rejected',()=>assert.throws(()=>importPortsCSV('id,x,y\np,1,2\np,3,4'),/Duplicate/));
test('boolean text false is false',()=>assert.equal(importPortsCSV('id,x,y,locked\np,1,2,false').ports[0].locked,false));
test('unknown boolean rejected',()=>assert.throws(()=>importPortsCSV('id,x,y,locked\np,1,2,nope'),/boolean/));
test('CSV export/import retains formula-leading and apostrophe text safely',()=>{const p=fixture();p.ports[0].id='=CMD()';p.ports[0].label="'literal";p.ports[0].net='@NET';p.ports[0].pair='DIFF';p.ports[0].polarity='+';const csv=exportPortsCSV(p);assert.match(csv,/'=CMD/);assert.match(csv,/apostrophe-v1/);assert.deepEqual(importPortsCSV(csv).ports,p.ports);});
test('assignment CSV roundtrip ignores informational columns',()=>{const p=fixture();assert.deepEqual(importConnectionsCSV(exportConnectionsCSV(p)),p.connections);});
test('array generation has unique multiletter row labels',()=>{const ports=generateArray({rows:24,columns:3});assert.equal(new Set(ports.map(n=>n.id)).size,72);assert.equal(rowLabel(20),'AA');});
test('array reserves requested labels',()=>assert.equal(generateArray({rows:1,columns:1,reserved:['A1']})[0].role,'reserved'));
test('array resource cap enforced',()=>assert.throws(()=>generateArray({rows:101,columns:100}),/10000/));
const lef=`VERSION 5.8 ; UNITS DATABASE MICRONS 2000 ; END UNITS\nMACRO chip\n ORIGIN 0 0 ; SIZE 100 BY 200 ;\n PIN VDD\n USE POWER ; PORT LAYER M4 ; RECT 10 20 30 40 ; END\n END VDD\n PIN D\n USE SIGNAL ; PORT LAYER M5 ; RECT 50 60 70 80 ; END\n END D\n OBS LAYER M4 ; RECT 1 1 2 2 ; END\nEND chip\nEND LIBRARY`;
test('LEF parses pin RECT centres, not obstruction or DBU scaling',()=>{const r=importLEF(lef);assert.equal(r.ports.length,2);assert.equal(r.ports[0].x,20);assert.equal(r.ports[0].y,30);assert.equal(r.ports[0].role,'power');assert.equal(r.die.height,200);});
test('LEF multiple macros require explicit selection',()=>assert.throws(()=>importLEF(lef+'\nMACRO other SIZE 5 BY 5 ; END other'),/Multiple/));
test('LEF selects explicit macro',()=>assert.equal(importLEF(lef,{macroName:'chip'}).die.name,'chip'));
test('LEF nonzero origin fails explicitly',()=>assert.throws(()=>importLEF(lef.replace('ORIGIN 0 0','ORIGIN 1 0')),/Nonzero/));
test('LEF polygons fail explicitly',()=>assert.throws(()=>importLEF(lef.replace('RECT 10 20 30 40','POLYGON 10 20 30 40')),/unsupported/));
test('LEF iterated geometry fails explicitly',()=>assert.throws(()=>importLEF(lef.replace('RECT 10 20 30 40','RECT ITERATE 10 20 30 40')),/unsupported/));
test('LEF never silently drops a shapeless pin',()=>assert.throws(()=>importLEF(lef.replace('RECT 10 20 30 40 ;','')),/No pin/));
test('LEF multiple rectangles produce an approximation warning',()=>assert.ok(importLEF(lef.replace('RECT 10 20 30 40 ;','RECT 10 20 30 40 ; RECT 40 20 60 40 ;')).warnings.some(s=>s.includes('bounding-box'))));
test('JSON unsupported version rejected',()=>assert.throws(()=>importJSON('{"schemaVersion":99}'),/Unsupported/));
