import test from 'node:test';import assert from 'node:assert/strict';import {analyze,regressionCheck} from '../src/core/rules.js';import {normalizeProject,emptyProject} from '../src/core/model.js';import {fixture,withGround,pairFixture,codes,synthetic} from './helpers.mjs';
test('baseline fixture is clean',()=>assert.equal(analyze(fixture()).ready,true));
test('empty design cannot pass review',()=>assert.ok(codes(analyze(emptyProject())).has('EMPTY_DESIGN')));
for(const [name,code,mutate] of [
 ['required unmapped site','UNASSIGNED',p=>p.connections=[]],['reserved site','FORBIDDEN_SITE',p=>p.ports[1].role='reserved'],['no-connect site','FORBIDDEN_SITE',p=>p.ports[1].role='nc'],['voltage mismatch','DOMAIN_CONFLICT',p=>p.ports[1].domain='V2'],['net conflict','NET_CONFLICT',p=>p.ports[1].net='OTHER'],['role mismatch','ROLE_CONFLICT',p=>p.ports[1].role='power'],['excessive length','MAX_LENGTH',p=>p.rules.maxLength=99],['missing domain','DOMAIN_UNSPECIFIED',p=>p.ports[0].domain=''],['missing net','NET_UNSPECIFIED',p=>p.ports[0].net=''],['clock shielding','CLOCK_SHIELD',p=>{p.ports[0].role='clock';p.rules.clockGroundMin=1;}],['ground coverage','GROUND_COVERAGE',p=>p.rules.groundRadius=200],['power coverage','POWER_COVERAGE',p=>{p.rules.requirePowerForSignals=true;p.rules.powerRadius=200;}],['ground fraction','GROUND_RATIO',p=>p.rules.minGroundRatio=.2],['path truncation','PATH_INCOMPLETE',p=>{p.rules.requireCompletePaths=true;p.rules.terminalKind='pcb';}],['forward stage rule','STAGE_ORDER',p=>p.rules.allowedStagePairs=[['pad','bump']]],['region ground quota','REGION_GROUND',p=>p.regions=[{id:'R',x:0,y:0,width:1000,height:1000,kind:'ball',domain:'',minGround:1,minPower:0}]],['region power quota','REGION_POWER',p=>p.regions=[{id:'R',x:0,y:0,width:1000,height:1000,kind:'ball',domain:'V1',minGround:0,minPower:1}]]
])test(`reports ${name}`,()=>{const p=fixture();mutate(p);assert.ok(codes(analyze(p)).has(code));});
test('multiple incoming mappings rejected by DRC',()=>{const p=fixture();p.ports.push({...p.ports[0],id:'s2'});p.connections.push({...p.connections[0],id:'e2',from:'s2'});assert.ok(codes(analyze(p)).has('MULTIPLE_DRIVERS'));});
test('physical site fanout rejected by DRC',()=>{const p=fixture();p.ports.push({...p.ports[1],id:'t2'});p.connections.push({...p.connections[0],id:'e2',to:'t2'});assert.ok(codes(analyze(p)).has('FANOUT'));});
test('connected ground satisfies coverage',()=>{const p=withGround();p.rules.groundRadius=150;p.rules.minGroundRatio=.5;assert.equal(analyze(p).errors,0);});
test('unconnected ground does not fake shielding',()=>{const p=withGround();p.connections.pop();p.rules.groundRadius=150;assert.ok(codes(analyze(p)).has('GROUND_COVERAGE'));});
test('domain-matched supply required for power coverage',()=>{const p=withGround();p.ports.find(n=>n.id==='gs').role='power';p.ports.find(n=>n.id==='gs').net='VDD';p.ports.find(n=>n.id==='gs').domain='V2';p.rules.requirePowerForSignals=true;p.rules.powerRadius=150;assert.ok(codes(analyze(p)).has('POWER_COVERAGE'));});
test('pair baseline satisfies adjacency and skew',()=>assert.equal(analyze(pairFixture()).errors,0));
test('pair adjacency enforced',()=>{const p=pairFixture();p.ports.find(n=>n.id==='t2').y=500;assert.ok(codes(analyze(p)).has('PAIR_ADJACENCY'));});
test('pair skew enforced',()=>{const p=pairFixture();p.ports.find(n=>n.id==='t2').x=250;assert.ok(codes(analyze(p)).has('PAIR_SKEW'));});
test('target pair polarity constraints enforced',()=>{const p=pairFixture();p.ports[1].pair='DIFF';p.ports[1].polarity='-';assert.ok(codes(analyze(p)).has('PAIR_POLARITY'));});
test('incomplete pair still blocks review',()=>{const p=pairFixture();p.connections.pop();assert.ok(codes(analyze(p)).has('PAIR_INCOMPLETE'));assert.equal(analyze(p).ready,false);});
test('different voltage domains must meet physical spacing',()=>{const p=pairFixture();p.ports.find(n=>n.id==='s2').domain='V2';p.rules.minDomainSpacing=150;assert.ok(codes(analyze(p)).has('DOMAIN_SPACING'));});
for(const [name,code,die]of [['outside die','OUTSIDE_DIE',{width:50,height:50}],['edge keep-out','EDGE_KEEPOUT',{edgeKeepout:10}],['corner keep-out','CORNER_KEEPOUT',{cornerKeepout:10}]])test(name,()=>{const p=fixture();p.dies=[{id:'D',name:'D',x:0,y:0,width:1000,height:1000,rotation:0,mirrorX:false,edgeKeepout:0,cornerKeepout:0,...die}];p.ports[0].dieId='D';if(name==='outside die')p.ports[0].x=70;assert.ok(codes(analyze(p)).has(code));});
test('occupied rectangle keep-out rejected',()=>{const p=fixture();p.keepouts=[{id:'K',dieId:'',kinds:['ball'],x:99,y:-1,width:2,height:2}];assert.ok(codes(analyze(p)).has('KEEPOUT'));});
test('unoccupied candidate in keep-out is allowed',()=>{const p=fixture();p.ports.push({...p.ports[1],id:'spare',x:500});p.keepouts=[{id:'K',dieId:'',kinds:['ball'],x:499,y:-1,width:2,height:2}];assert.ok(!codes(analyze(p)).has('KEEPOUT'));});
test('duplicate physical sites reported',()=>{const p=pairFixture();p.ports.find(n=>n.id==='t2').y=0;assert.ok(codes(analyze(p)).has('SITE_COLLISION'));});
test('exhausted budget can never produce clean review',()=>{const p=synthetic(40,{crossed:true});p.rules.geometryBudget=100;const a=analyze(p);assert.equal(a.complete,false);assert.equal(a.ready,false);assert.ok(codes(a).has('ANALYSIS_INCOMPLETE'));});
test('reserved JS property names are safe connection identifiers',()=>{const p=fixture();p.connections[0].id='__proto__';assert.equal(analyze(p).lengths.__proto__,100);});
test('regression gate blocks newly introduced hard errors',()=>{const p=fixture(),before=analyze(p);p.ports[1].net='BAD';assert.equal(regressionCheck(before,analyze(p)).ok,false);});
