import { VERSION, KINDS, ROLES, clone, emptyProject, normalizeProject, effectiveSignals, worldPoint, inversePoint, rank, connect, disconnect, portAt, fingerprint } from './core/model.js';
import { analyze, compatible } from './core/rules.js';
import { ProjectStore, compareProjects } from './core/revisions.js';
import { demoProject } from './core/demo.js';
import { importJSON, importPortsCSV, importConnectionsCSV, importLEF, generateArray } from './core/importers.js';
import { escapeHTML, LAYER_COLORS, ROLE_COLORS, diagram, exportJSON, exportPortsCSV, exportConnectionsCSV, exportSVG, exportPDF, exportICDHTML, exportICDMarkdown } from './core/exporters.js';
const $ = id => document.getElementById(id), esc=escapeHTML;
const storageKey='openbumpplan.project.v1';
let saveStatus='Not yet saved — export JSON';
let initial=demoProject(),restoreError='';
try {const saved=localStorage.getItem(storageKey);if(saved)initial=importJSON(saved);}catch(e){restoreError=`Local restore failed: ${e.message}. Synthetic demo loaded.`;}
let store=new ProjectStore(initial),baseline=clone(initial),tab='plan',selected='',mode='inspect',view='physical',layers=[...KINDS],strict=true,labels=true,overlay=false,viewBox=null,mapLayout=null,drag=null,search='',tablePage=0,issueFilter='all',worker=null,workerURL=null,pendingImport=null,toastTimer=null,fromStage='interposer',toStage='ball',snapStep=10;
function toast(message,error=false) {$('toast').textContent=message;$('toast').className=`show${error?' error':''}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),6500);}
function persist() {try{localStorage.setItem(storageKey,exportJSON(store.project));saveStatus='Saved on this device';$('saveState').textContent=saveStatus;}catch{saveStatus='Local save unavailable — export JSON';$('saveState').textContent=saveStatus;toast('Local storage is unavailable/full. Export JSON to keep your work.',true);}}
function mutate(action,fn,options={}) {try{store.transact(action,fn,{strict,...options});render();persist();return true;}catch(e){toast(e.message,true);return false;}}
function metricNumber(n) {return Number(n).toLocaleString('en-US',{maximumFractionDigits:1});}
function option(value,label=value,current='',disabled=false){return `<option value="${esc(value)}" ${value===current?'selected':''} ${disabled?'disabled':''}>${esc(label)}</option>`;}
function field(label,name,value,type='text',extra=''){return `<label>${esc(label)}<input name="${esc(name)}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function selectField(label,name,values,value){return `<label>${esc(label)}<select name="${esc(name)}">${values.map(v=>Array.isArray(v)?option(v[0],v[1],value):option(v,v,value)).join('')}</select></label>`;}
function controls(){return `<button data-action="new" title="Create an empty project">New</button><button data-action="demo">Demo</button><button data-action="import">Import</button><button data-action="export-json" class="primary">Save JSON</button><select id="exportSelect" aria-label="Export format"><option value="">Export…</option><option value="ports">Ports CSV</option><option value="connections">Assignments CSV</option><option value="svg">Map SVG</option><option value="pdf">ICD PDF</option><option value="html">ICD HTML</option><option value="md">ICD Markdown</option><option value="validation">Validation JSON</option><option value="diff">Revision diff JSON</option></select><button data-action="help" aria-label="Help and keyboard shortcuts">?</button>`;}
function render(){
  const p=store.project,a=store.analysis,m=a.metrics;
  $('app').innerHTML=`<header class="brandbar"><div class="brandicon" aria-hidden="true"></div><div><div class="brandname">OpenBumpPlan</div><div class="brandtag">DIE → PACKAGE → BOARD</div></div><span class="version">v${VERSION} · ALPHA</span><div class="spacer"></div><span class="privacy">● Local-only design data</span>${controls()}</header>
  <div class="projectbar"><span class="projectname" title="${esc(p.name)}">${esc(p.name)}</span><nav class="tabs" aria-label="Workspace views">${[['plan','Plan'],['connections','Connectivity'],['rules','Rules'],['revisions','Revisions'],['icd','Interface document']].map(([id,label])=>`<button data-tab="${id}" class="${tab===id?'active':''}" aria-current="${tab===id?'page':'false'}">${label}</button>`).join('')}</nav><div class="spacer"></div><span class="pill">r${p.revision}</span></div>
  <section class="metrics" aria-label="Planning metrics"><div class="metric"><div class="label">Configured-rule review</div><div class="value ${a.errors?'bad':a.warnings?'warn':'good'}">${!a.complete?'Incomplete':a.errors?`${a.errors} errors`:a.warnings?'Review warnings':'Checks pass'}</div><div class="detail">${a.warnings} warnings · planning only, not signoff</div></div><div class="metric"><div class="label">Manhattan length</div><div class="value">${metricNumber(m.totalLength/1000)}<span class="unit">mm total</span></div><div class="detail">Longest ${metricNumber(m.maxLength)} um · physical XY</div></div><div class="metric"><div class="label">Ratsnest crossings</div><div class="value ${m.crossings?'warn':''}">${m.crossings}${!a.complete?'+':''}<span class="unit">same stage</span></div><div class="detail">${m.overlaps} collinear overlaps, separate from score</div></div><div class="metric"><div class="label">Assigned paths</div><div class="value">${m.connections}<span class="unit">links / ${m.ports} sites</span></div><div class="detail">${m.unassigned} required sites unassigned</div></div><div class="metric"><div class="label">Planning objective</div><div class="value">${metricNumber(m.score)}${!a.complete?'+':''}</div><div class="detail">L1 + ${p.rules.crossingWeight} × crossings · lower is better</div></div></section>
  <main id="workspace">${tab==='plan'?planPage():tab==='connections'?connectionsPage():tab==='rules'?rulesPage():tab==='revisions'?revisionsPage():icdPage()}</main>
  <footer class="footer"><span id="saveState">${esc(saveStatus)}</span><span>Review ID ${fingerprint(p)}</span><span class="spacer"></span><span>Geometric planning ≠ SI / PI / routing / signoff</span><button class="quiet" data-action="advanced" style="font-size:10px;padding:2px 6px">Project JSON</button></footer>`;
  $('exportSelect').addEventListener('change',e=>{if(e.target.value)downloadExport(e.target.value);e.target.value='';});
  if(tab==='plan')renderMap();
  if(tab==='connections'){$('connectionSearch').addEventListener('input',e=>{search=e.target.value;tablePage=0;renderConnectionRows();});renderConnectionRows();}
  if(tab==='icd')$('icdFrame').srcdoc=exportICDHTML(p);
}
function planPage(){const p=store.project;return `<div class="workspace"><aside class="panel left"><div class="section"><div class="eyebrow">Physical stack</div>${KINDS.map(k=>`<label class="layer"><input type="checkbox" data-layer="${k}" ${layers.includes(k)?'checked':''}><span class="dot" style="background:${LAYER_COLORS[k]}"></span>${k[0].toUpperCase()+k.slice(1)}<span class="count">${p.ports.filter(n=>n.kind===k).length}</span></label>`).join('')}</div><div class="section"><div class="eyebrow">Die placement</div>${p.dies.map(d=>`<button class="diebutton" data-die="${esc(d.id)}">${esc(d.name)}<small>${d.width} × ${d.height} um · R${d.rotation}${d.mirrorX?' · mirror X':''}</small></button>`).join('')||'<p class="hint">Import a LEF macro or add a die in Project JSON.</p>'}</div><div class="section"><div class="eyebrow">Assignment optimizer</div><div class="stackform">${selectField('From layer','fromStage',KINDS,fromStage)}${selectField('To layer','toStage',KINDS,toStage)}<button data-action="optimize" class="primary" ${worker?'disabled':''}>Optimize stage</button>${worker?'<div class="busy"><span class="spinner"></span>Checking candidate mappings…</div><button data-action="cancel-optimize">Cancel</button>':''}</div><p class="hint">Pair-aware placement + minimum-cost assignment + checked swaps. Locked mappings are preserved.</p></div><div class="section"><button data-action="array" style="width:100%">Generate bump / ball array</button><p class="hint">Use explicit units and voltage domains. Imports are previewed before application.</p></div></aside>
  <section class="canvasarea" aria-label="Interactive planning canvas"><div class="canvasbar"><div class="modes">${['inspect','move','connect'].map(m=>`<button data-mode="${m}" class="${mode===m?'active':''}">${m[0].toUpperCase()+m.slice(1)}</button>`).join('')}</div><select id="viewSelect" aria-label="Physical or exploded view">${option('physical','Physical XY',view)}${option('exploded','Exploded stack',view)}</select><button data-action="fit">Fit</button><button data-action="undo" title="Ctrl/Cmd+Z" ${store.undoStack.length?'':'disabled'}>↶</button><button data-action="redo" title="Ctrl/Cmd+Shift+Z" ${store.redoStack.length?'':'disabled'}>↷</button><div class="spacer"></div><label title="Local coordinate snap step in micrometres">Snap <input id="snap" type="number" min="0" value="${snapStep}" aria-label="Snap step in micrometres"></label></div><div class="canvaswrap"><svg id="map" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Interactive die and package map"><g id="mapBody"></g></svg><div class="canvaslegend">${Object.entries(ROLE_COLORS).filter(([k])=>k!=='any').map(([k,c])=>`<span style="margin-right:10px"><i class="legend-dot" style="background:${c}"></i>${k}</span>`).join('')}<br><b>${mode==='connect'?'Drag source to destination, or select a source and click its destination.':mode==='move'?'Drag a site to move it. Locked sites cannot move.':'Select a site to inspect its net and assignments.'}</b> Scroll to zoom · drag background to pan</div></div><div class="canvasfoot"><label><input id="strictToggle" type="checkbox" ${strict?'checked':''}> Block new hard-rule violations</label><label><input id="labelToggle" type="checkbox" ${labels?'checked':''}> Labels</label><label><input id="overlayToggle" type="checkbox" ${overlay?'checked':''}> Baseline overlay</label><span class="spacer"></span><span>${view==='exploded'?'Display offsets only; scores use physical XY':'Package coordinates · um · Y↑'}</span></div></section>
  <aside class="panel right">${inspector()}<div class="section inline"><h3>Rule findings</h3><span class="spacer"></span><select id="issueFilter" aria-label="Filter findings">${option('all','All',issueFilter)}${option('error','Errors',issueFilter)}${option('warning','Warnings',issueFilter)}</select></div>${issueList()}</aside></div>`;}
function inspector(){const n=store.project.ports.find(p=>p.id===selected);if(!n)return `<div class="section"><div class="eyebrow">Inspector</div><h3>Every assignment, explained.</h3><p class="hint">Select a pad, bump, ball, or PCB site. Review inherited nets, move sites, and reassign connections without losing revision history.</p></div>`;
  const p=store.project,ctx=effectiveSignals(p),s=ctx.signals.get(n.id),targets=p.ports.filter(t=>rank(t.kind)>rank(n.kind)&&p.rules.allowedStagePairs.some(([a,b])=>a===n.kind&&b===t.kind));
  return `<div class="section"><div class="eyebrow">Selected ${esc(n.kind)} ${n.locked?'· locked':''}</div><h3 class="inspector-title">${esc(n.id)}</h3><p class="hint" style="margin-bottom:12px">Effective: <strong>${esc(s.net||'(unassigned)')}</strong> / ${esc(s.domain||'no domain')} / ${esc(s.role)}</p><form data-form="port" class="formgrid">${field('Local / package X (um)','x',n.x,'number','step="any" '+(n.locked?'disabled':''))}${field('Local / package Y (um)','y',n.y,'number','step="any" '+(n.locked?'disabled':''))}${field('Declared net (blank = inherit)','net',n.net)}${field('Voltage domain','domain',n.domain)}${selectField('Site role','role',ROLES,n.role)}${field('Display label','label',n.label)}${field('Differential-pair ID','pair',n.pair)}${selectField('Polarity','polarity',[['','None'],['+','+'],['-','-']],n.polarity)}<label class="full"><input type="checkbox" name="required" ${n.required?'checked':''}> Required interface site</label><button class="full" type="submit">Apply site edits</button></form><div class="actions"><button data-action="lock">${n.locked?'Unlock':'Lock site'}</button><button data-action="disconnect" class="danger">Disconnect</button></div>${targets.length?`<form data-form="assign" style="margin-top:16px"><label>Assign to destination<select name="target"><option value="">Select a target…</option>${targets.map(t=>option(t.id,`${t.id}${ctx.incoming.has(t.id)?' · occupied':''}${compatible(n,t,p,ctx)?'':' · incompatible'}`,'',t.locked||strict&&!compatible(n,t,p,ctx))).join('')}</select></label><label style="margin-top:8px"><input name="replace" type="checkbox"> Replace occupied source / target mapping</label><button type="submit" class="primary" style="width:100%;margin-top:9px" ${n.locked?'disabled':''}>Assign connection</button></form>`:''}</div>`;}
function issueList(){const a=store.analysis,items=a.issues.filter(i=>issueFilter==='all'||i.severity===issueFilter);if(!items.length)return `<div class="empty"><div class="symbol">✓</div>No ${issueFilter==='all'?'configured-rule':issueFilter} findings.<br>Planning checks do not replace engineering signoff.</div>`;
  return items.slice(0,150).map((i,index)=>`<button class="issue ${i.severity}" data-issue="${a.issues.indexOf(i)}"><span class="code">${esc(i.code)}</span><span class="message">${esc(i.message)}</span></button>`).join('')+(items.length>150?`<div class="empty">Showing 150 of ${items.length} findings. Export validation JSON for all retained details.</div>`:'');}
function renderMap(){const p=store.project;mapLayout=diagram(p,{view,layers,selected,showLabels:labels,baseline:overlay?baseline:null});$('mapBody').innerHTML=mapLayout.body;if(!viewBox){const b=mapLayout.bounds;viewBox=[b.x,b.y,b.width,b.height];}setViewBox();const svg=$('map');svg.removeEventListener('wheel',zoom);svg.addEventListener('wheel',zoom,{passive:false});svg.onpointerdown=pointerDown;svg.onpointermove=pointerMove;svg.onpointerup=pointerUp;svg.onpointercancel=()=>{drag=null;renderMap();};}
function setViewBox(){if($('map')&&viewBox)$('map').setAttribute('viewBox',viewBox.join(' '));}
function svgPoint(event){const svg=$('map'),point=svg.createSVGPoint();point.x=event.clientX;point.y=event.clientY;return point.matrixTransform(svg.getScreenCTM().inverse());}
function zoom(e){e.preventDefault();const q=svgPoint(e),factor=Math.exp(Math.max(-600,Math.min(600,e.deltaY))*.0015),width=viewBox[2]*factor;if(width<100||width>2000000)return;viewBox=[q.x+(viewBox[0]-q.x)*factor,q.y+(viewBox[1]-q.y)*factor,width,viewBox[3]*factor];setViewBox();}
function pointerDown(e){if(e.button!==0)return;const el=e.target.closest('[data-port]'),id=el?.dataset.port;
  if(id&&mode==='move'){const n=portAt(store.project,id);if(n.locked){toast('This site is locked.',true);return;}drag={type:'move',id,element:el,start:svgPoint(e),node:clone(n),origin:mapLayout.nodes.find(x=>x.id===id),moved:false};$('map').setPointerCapture(e.pointerId);}
  else if(id){drag={type:mode==='connect'?'connect':'select',id,clientX:e.clientX,clientY:e.clientY,moved:false};}
  else{const matrix=$('map').getScreenCTM();drag={type:'pan',clientX:e.clientX,clientY:e.clientY,box:[...viewBox],scaleX:matrix.a,scaleY:matrix.d};$('map').setPointerCapture(e.pointerId);}}
function pointerMove(e){if(!drag)return;
  if(drag.type==='pan'){viewBox=[drag.box[0]-(e.clientX-drag.clientX)/drag.scaleX,drag.box[1]-(e.clientY-drag.clientY)/drag.scaleY,drag.box[2],drag.box[3]];setViewBox();}
  else if(drag.type==='move'){const q=svgPoint(e),dx=q.x-drag.start.x,dy=q.y-drag.start.y;drag.moved=Math.abs(dx)+Math.abs(dy)>1;drag.q={x:drag.origin.sx+dx,y:drag.origin.sy+dy};drag.element.setAttribute('transform',`translate(${dx} ${dy})`);for(const line of $('map').querySelectorAll('[data-edge]')){const edge=store.project.connections.find(x=>x.id===line.dataset.edge);if(edge.from===drag.id){line.setAttribute('x1',drag.q.x);line.setAttribute('y1',drag.q.y);}if(edge.to===drag.id){line.setAttribute('x2',drag.q.x);line.setAttribute('y2',drag.q.y);}}}
  else if(Math.abs(e.clientX-drag.clientX)+Math.abs(e.clientY-drag.clientY)>5)drag.moved=true;
}
function pointerUp(e){if(!drag)return;const d=drag;drag=null;
  if(d.type==='move'){selected=d.id;if(d.moved&&d.q){const world={x:d.q.x-mapLayout.offsets[d.node.kind],y:-d.q.y},local=inversePoint(world,mapLayout.ctx.dies.get(d.node.dieId)),snap=Math.max(0,Number($('snap').value)||0);mutate(`Move ${d.id}`,p=>{const n=portAt(p,d.id);n.x=snap?Math.round(local.x/snap)*snap:local.x;n.y=snap?Math.round(local.y/snap)*snap:local.y;});}render();}
  else if(d.type==='select')selectPort(d.id);
  else if(d.type==='connect'){const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-port]')?.dataset.port;if(d.moved&&hit&&hit!==d.id){selected=d.id;assign(d.id,hit,false);}else if(selected&&selected!==d.id&&rank(portAt(store.project,selected).kind)<rank(portAt(store.project,d.id).kind))assign(selected,d.id,false);else selectPort(d.id);}}
function selectPort(id){selected=id;render();}
function assign(from,to,replace){if(!to){toast('Choose a destination.',true);return;}if(mutate(`Assign ${from} to ${to}`,p=>connect(p,from,to,{replace})))toast('Assignment updated. Undo is available.');}
function connectionsPage(){return `<section class="contentpage"><div class="pageheading"><div><h2>Connectivity, across the stack</h2><p class="hint">Logical nets propagate through every assignment. Declared constraints never silently change.</p></div><span class="spacer"></span><input id="connectionSearch" placeholder="Search a net, domain, or endpoint" aria-label="Search connections" value="${esc(search)}" style="width:280px"><button data-action="export-connections">Export CSV</button></div><div class="tablewrap"><table><thead><tr><th>Source</th><th>Destination</th><th>Net / pair</th><th>Domain</th><th>Role</th><th>L1 · um</th><th>Locked</th></tr></thead><tbody id="connectionRows"></tbody></table></div><div class="actions"><button data-action="previous-page">Previous</button><span id="tableCount" class="hint"></span><button data-action="next-page">Next</button></div></section>`;}
function filteredConnections(){const ctx=effectiveSignals(store.project),q=search.toLowerCase();return store.project.connections.filter(e=>[e.from,e.to,ctx.signals.get(e.from).net,ctx.signals.get(e.from).domain].some(s=>s.toLowerCase().includes(q)));}
function renderConnectionRows(){const p=store.project,ctx=effectiveSignals(p),rows=filteredConnections(),pages=Math.max(1,Math.ceil(rows.length/100));tablePage=Math.max(0,Math.min(tablePage,pages-1));$('connectionRows').innerHTML=rows.slice(tablePage*100,(tablePage+1)*100).map(e=>{const s=ctx.signals.get(e.from);return `<tr><td><button class="linkbutton" data-select="${esc(e.from)}">${esc(e.from)}</button></td><td><button class="linkbutton" data-select="${esc(e.to)}">${esc(e.to)}</button></td><td>${esc(s.net||'(unnamed)')}${s.pair?`<br><small>${esc(s.pair)} ${esc(s.polarity)}</small>`:''}</td><td>${esc(s.domain||'—')}</td><td>${esc(s.role)}</td><td>${metricNumber(store.analysis.lengths[e.id])}</td><td><button class="quiet" data-edge-lock="${esc(e.id)}" style="padding:3px 6px;font-size:10px">${e.locked?'Locked':'Unlocked'}</button></td></tr>`;}).join('')||'<tr><td colspan="7">No matching assignments.</td></tr>';$('tableCount').textContent=`Page ${tablePage+1}/${pages} · ${rows.length} matching assignments`;}
const ruleLabels={maxLength:'Maximum assignment L1 (um)',minDomainSpacing:'Different-domain Euclidean spacing (um)',pairMaxDistance:'Pair adjacency, L1 (um)',pairMaxSkew:'Pair L1 skew limit (um)',clockShieldRadius:'Clock ground-neighbour radius (um)',clockGroundMin:'Minimum clock ground neighbours',groundRadius:'Signal ground coverage radius (um)',powerRadius:'Signal power coverage radius (um)',minGroundRatio:'Minimum connected ground fraction (0–1)',crossingWeight:'Crossing cost, um-equivalent',maxCrossings:'Crossing warning threshold',geometryBudget:'Geometry comparison safety budget'};
function rulesPage(){const p=store.project,r=p.rules;return `<section class="contentpage"><div class="pageheading"><div><h2>Explicit constraints. Reproducible checks.</h2><p class="hint">Editing rules re-evaluates the design; it does not automatically repair or approve mappings.</p></div><span class="spacer"></span><button data-action="export-validation">Export findings</button></div><form data-form="rules"><div class="card"><div class="rulegrid">${Object.entries(ruleLabels).map(([key,label])=>field(label,key,r[key],'number','min="0" step="any" required')).join('')}${selectField('Terminal interface layer','terminalKind',KINDS,r.terminalKind)}<label style="padding-top:20px"><input name="requirePowerForSignals" type="checkbox" ${r.requirePowerForSignals?'checked':''}> Enforce domain-matched power coverage</label><label style="padding-top:20px"><input name="requireCompletePaths" type="checkbox" ${r.requireCompletePaths?'checked':''}> Require paths to the terminal layer</label></div><div class="actions"><button type="submit" class="primary">Apply rules and recheck</button></div></div></form><div class="twocol"><div class="card"><h3>Geometric proxies, not electrical signoff</h3><p>Distances use physical package XY. Signal and clock ground neighbours must be connected ground sites on the same layer. A power neighbour must also match the signal’s voltage domain.</p><p>Differential adjacency is L1 distance; ground proximity and voltage-domain spacing are Euclidean. Skew is the difference of L1 assignment lengths within each stage, not measured electrical delay.</p></div><div class="card"><h3>Draft editing and strict checks</h3><p>Strict mapping edits block newly introduced hard-rule violations. Missing assignments, nets, domains, and incomplete pairs/paths may remain while building a draft; they still prevent review readiness.</p><p>Budget exhaustion is an error. Crossings are same-stage straight-ratsnest intersections, not routing shorts. Collinear overlaps are reported separately.</p></div></div><div class="card"><h3>Keep-outs, P/G quotas, and stage topology</h3><p>Edit rectangle keep-outs, die edge/corner distances, per-region power/ground quotas, and allowed forward stages in the complete project JSON. All inputs are validated before use.</p><button data-action="advanced">Edit complete project JSON</button><pre class="mono" style="font-size:11px;white-space:pre-wrap;margin-top:15px">${esc(JSON.stringify({keepouts:p.keepouts,regions:p.regions,allowedStagePairs:r.allowedStagePairs},null,2))}</pre></div></section>`;}
function revisionsPage(){const d=compareProjects(baseline,store.project),s=d.summary;return `<section class="contentpage"><div class="pageheading"><div><h2>Revision review</h2><p class="hint">Baseline ${d.beforeFingerprint} → current ${d.afterFingerprint}. Includes propagated net changes and transformed physical movements.</p></div><span class="spacer"></span><button data-action="baseline-current">Set current as baseline</button><button data-action="baseline-import">Load baseline JSON</button><button data-action="export-diff">Export diff</button></div><div class="revisionstats">${[['Added',s.added],['Removed',s.removed],['Changed',s.changed],['Score delta',metricNumber(s.scoreDelta)]].map(([k,v])=>`<div class="card"><div class="eyebrow">${k}</div><div class="big">${v}</div></div>`).join('')}</div><div class="notice ${d.gate.ok?'':'bad'}">${d.gate.ok?'Regression gate: no newly introduced hard or incomplete-interface errors.':'Regression gate blocked: '+esc(d.gate.reason)} This gate is not a manufacturing approval.</div><div class="tablewrap"><table><thead><tr><th>Change</th><th>Object</th><th>Identifier</th><th>Changed fields</th></tr></thead><tbody>${d.changes.slice(0,500).map(c=>`<tr><td>${c.type}</td><td>${c.category}</td><td>${esc(c.id)}</td><td>${esc(c.fields?.join(', ')||'—')}</td></tr>`).join('')||'<tr><td colspan="4">No structural differences from the baseline.</td></tr>'}</tbody></table></div><div class="card"><h3>Downstream effects · ${d.propagated.length} sites</h3><p>These may change even when a port’s own record does not — for example, after a die rotation or an upstream reassignment.</p><div class="tablewrap"><table><thead><tr><th>Site</th><th>Physical movement, L1 (um)</th><th>Previous net</th><th>Current net</th></tr></thead><tbody>${d.propagated.slice(0,500).map(v=>`<tr><td>${esc(v.id)}</td><td>${metricNumber(v.movement)}</td><td>${esc(v.signalBefore.net)}</td><td>${esc(v.signalAfter.net)}</td></tr>`).join('')||'<tr><td colspan="4">No propagated changes.</td></tr>'}</tbody></table></div></div><p class="hint">Tables show up to 500 entries each; exported diff contains all changes. Local undo/audit records are convenient review aids, not signed approvals.</p></section>`;}
function icdPage(){return `<section class="contentpage"><div class="pageheading"><div><h2>Interface-control document</h2><p class="hint">Mechanical transforms, connectivity, rules, metrics, findings, and approval fields — generated from the current revision.</p></div><span class="spacer"></span><button data-action="export-md">Markdown</button><button data-action="export-html">HTML</button><button class="primary" data-action="export-pdf">Download PDF</button></div><iframe id="icdFrame" class="icdframe" title="Interface-control document preview" sandbox=""></iframe></section>`;}
function openDialog(title,description,body,buttons=''){pendingImport=null;$('dialog').innerHTML=`<h2>${esc(title)}</h2><p>${esc(description)}</p>${body}<div id="dialogError" class="error" role="alert"></div><div class="actions"><button type="button" data-action="close-dialog">Cancel</button>${buttons}</div>`;$('dialog').showModal();}
function closeDialog(){$('dialog').close();pendingImport=null;}
function importDialog(){openDialog('Import interface data','Imports are local. Preview first; no existing object is silently overwritten.',`<div class="formgrid">${selectField('Input format','importType',[['json','Complete project JSON'],['ports','Ports CSV'],['connections','Assignments CSV'],['lef','LEF macro (RECT subset)']],'json')}${selectField('CSV site layer','importKind',KINDS,'pad')}${selectField('CSV coordinate units','importUnits',['um','mm','nm'],'um')}${field('Die ID (blank = package XY)','importDie','')}${field('LEF macro name (required for multi-macro LEF)','macroName','')}<label>Choose file<input id="importFile" type="file" accept=".json,.csv,.lef,.txt"></label><label class="full">Or paste text<textarea id="importText" spellcheck="false" style="min-height:130px" placeholder="Paste JSON, CSV, or LEF here"></textarea></label></div><div id="importPreview"></div>`,`<button data-action="preview-import">Preview and validate</button><button id="applyImport" data-action="apply-import" class="primary" disabled>Apply import</button>`);}
async function previewImport(){try{const dialog=$('dialog'),value=name=>dialog.querySelector(`[name="${name}"]`).value;const text=$('importText').value||await $('importFile').files[0]?.text();if(!text)throw new Error('Choose a file or paste text.');const type=value('importType'),candidate=clone(store.project);let notes=[];
  if(type==='json')Object.assign(candidate,importJSON(text));
  else if(type==='ports'){const result=importPortsCSV(text,{kind:value('importKind'),dieId:value('importDie'),units:value('importUnits')});candidate.ports.push(...result.ports);notes=result.warnings;}
  else if(type==='connections')candidate.connections.push(...importConnectionsCSV(text));
  else{const result=importLEF(text,{macroName:value('macroName'),dieId:value('importDie')||'DIE'});candidate.dies.push(result.die);candidate.ports.push(...result.ports);notes=result.warnings;}
  const normalized=normalizeProject(candidate),a=analyze(normalized);pendingImport={candidate:normalized,type};$('importPreview').innerHTML=`<div class="notice ${a.errors?'warn':''}">Preview: ${normalized.dies.length} dies, ${normalized.ports.length} sites, ${normalized.connections.length} assignments. ${a.errors} rule errors and ${a.warnings} warnings.${notes.map(n=>`<br>${esc(n)}`).join('')}</div><p class="hint">Import may introduce a draft with rule violations. They remain visible and prevent readiness; no data is automatically repaired.</p>`;$('applyImport').disabled=false;$('dialogError').textContent='';
  }catch(e){pendingImport=null;$('applyImport').disabled=true;$('dialogError').textContent=e.message;}}
function arrayDialog(){openDialog('Generate an array','Creates candidate sites only; it never invents electrical connectivity. Coordinates are micrometres.',`<form id="arrayForm" class="formgrid">${field('Rows','rows',8,'number','min="1"')}${field('Columns','columns',8,'number','min="1"')}${field('Pitch (um)','pitch',500,'number','min="0.001" step="any"')}${selectField('Layer','kind',KINDS,'ball')}${field('Origin X (um)','x',0,'number','step="any"')}${field('Origin Y (um)','y',0,'number','step="any"')}${field('Unique ID prefix','prefix','BGA')}${field('Die ID (blank = package XY)','dieId','')}${selectField('Site role','role',ROLES,'any')}${field('Voltage domain (optional)','domain','')}</form>`,`<button data-action="create-array" class="primary">Create sites</button>`);}
function dieDialog(id){const d=store.project.dies.find(x=>x.id===id);openDialog(`Place ${d.name}`,'Mirror local X first, then rotate counter-clockwise about the local origin, then translate into package XY.',`<form id="dieForm" data-id="${esc(id)}" class="formgrid">${field('Name','name',d.name)}${selectField('Rotation','rotation',['0','90','180','270'],String(d.rotation))}${field('Origin X (um)','x',d.x,'number','step="any"')}${field('Origin Y (um)','y',d.y,'number','step="any"')}${field('Width (um)','width',d.width,'number','step="any"')}${field('Height (um)','height',d.height,'number','step="any"')}${field('Edge keep-out (um)','edgeKeepout',d.edgeKeepout,'number','step="any"')}${field('Corner keep-out radius (um)','cornerKeepout',d.cornerKeepout,'number','step="any"')}<label class="full"><input name="mirrorX" type="checkbox" ${d.mirrorX?'checked':''}> Mirror local X before rotation</label></form>`,`<button data-action="apply-die" class="primary">Apply transform</button>`);}
function advancedDialog(){openDialog('Complete project JSON','A versioned, open data model. Applying edits may create a draft with violations; all geometry and references are validated first.',`<textarea id="projectJSON" style="min-height:430px" spellcheck="false">${esc(exportJSON(store.project))}</textarea>`,`<button data-action="apply-json" class="primary">Validate and apply</button>`);}
function helpDialog(){openDialog('Planning workflow','This is an alpha planning application, not a fabrication or signoff tool.',`<div class="card"><h3>1. Load and inspect</h3><p>Start with the synthetic demo, or import CSV/LEF/JSON. CSV requires id,x,y. LEF supports rectangular PIN geometry only. All units are converted to micrometres.</p><h3>2. Assign and constrain</h3><p>Inspect selects sites. Move drags geometry. Connect drags or clicks a source then its target. Use the inspector’s Replace checkbox for occupied mappings. Strict mode blocks new hard violations, but permits explicitly reported incomplete drafts.</p><h3>3. Optimize and review</h3><p>The left panel optimizes one forward stage in a worker. Pair placement and a Hungarian subproblem produce candidates, then full rules validate them. This is a bounded heuristic, not a global coupled optimum.</p><h3>4. Compare and deliver</h3><p>Set a baseline before editing, compare propagated changes, and export the interface document. Save JSON for a lossless checkpoint. CSV formula-leading text is reversibly escaped.</p></div><p>Ctrl/Cmd+Z: undo · Ctrl/Cmd+Shift+Z: redo · F: fit canvas · Escape: cancel dialog · Enter on a focused site: inspect.</p><p>No accounts, telemetry, CDNs, or network uploads. A browser may restrict local storage; export JSON regularly. This tool has no SI/PI/thermal engine and no foundry-qualified signoff.</p>`,`<button data-action="close-dialog" class="primary">Start planning</button>`);}
function download(data,name,type){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function downloadExport(format){try{const p=store.project,prefix=`openbumpplan-r${p.revision}`;const outputs={json:()=>[exportJSON(p),`${prefix}.json`,'application/json'],ports:()=>[exportPortsCSV(p),`${prefix}-ports.csv`,'text/csv'],connections:()=>[exportConnectionsCSV(p),`${prefix}-assignments.csv`,'text/csv'],svg:()=>[exportSVG(p,{view,layers}),`${prefix}-map.svg`,'image/svg+xml'],pdf:()=>[exportPDF(p),`${prefix}-ICD.pdf`,'application/pdf'],html:()=>[exportICDHTML(p),`${prefix}-ICD.html`,'text/html'],md:()=>[exportICDMarkdown(p),`${prefix}-ICD.md`,'text/markdown'],validation:()=>[JSON.stringify(store.analysis,null,2),`${prefix}-validation.json`,'application/json'],diff:()=>[JSON.stringify(compareProjects(baseline,p),null,2),`${prefix}-diff.json`,'application/json']};if(!outputs[format])throw new Error('Unknown export format.');download(...outputs[format]());toast('Export created from the current revision.');}catch(e){toast(e.message,true);}}
function cancelWorker(){if(worker)worker.terminate();worker=null;if(workerURL)URL.revokeObjectURL(workerURL);workerURL=null;}
function optimize(){if(worker)return;const from=document.querySelector('[name="fromStage"]').value,to=document.querySelector('[name="toStage"]').value,revision=store.project.revision,inputFingerprint=fingerprint(store.project);try{
  if(globalThis.OPENBUMPPLAN_WORKER_SOURCE){workerURL=URL.createObjectURL(new Blob([globalThis.OPENBUMPPLAN_WORKER_SOURCE],{type:'text/javascript'}));worker=new Worker(workerURL);}else worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});
  worker.onmessage=event=>{cancelWorker();if(store.project.revision!==revision||fingerprint(store.project)!==inputFingerprint){render();toast('The design changed during optimization. Stale results were discarded.',true);return;}if(!event.data.ok){render();toast(event.data.error,true);return;}const result=event.data.result;if(result.changed){mutate(`Optimize ${from} -> ${to}`,p=>{p.connections=result.project.connections;},{strict:true});toast(`Checked optimization: score ${metricNumber(result.before.metrics.score)} → ${metricNumber(result.after.metrics.score)}; crossings ${result.before.metrics.crossings} → ${result.after.metrics.crossings}.`);}else{render();toast(result.message);}};
  worker.onerror=event=>{cancelWorker();render();toast(`Optimization worker failed: ${event.message}. No design changes were applied.`,true);};
  worker.postMessage({project:clone(store.project),from,to,options:{maxTrials:700}});render();
  }catch(e){cancelWorker();toast(e.message,true);}}
// Delegated handlers survive workspace re-rendering without accumulating listeners.
document.addEventListener('click',async e=>{
  const target=e.target.closest('button');if(!target)return;
  if(target.dataset.tab){tab=target.dataset.tab;render();return;}
  if(target.dataset.mode){mode=target.dataset.mode;render();return;}
  if(target.dataset.die){dieDialog(target.dataset.die);return;}
  if(target.dataset.select){tab='plan';selected=target.dataset.select;render();return;}
  if(target.dataset.edgeLock){mutate(`Toggle lock ${target.dataset.edgeLock}`,p=>{const edge=p.connections.find(x=>x.id===target.dataset.edgeLock);edge.locked=!edge.locked;});return;}
  if(target.dataset.issue!==undefined){const issue=store.analysis.issues[Number(target.dataset.issue)];if(issue.ports[0]){selected=issue.ports[0];render();}else toast(issue.message);return;}
  const action=target.dataset.action;if(!action)return;
  try{
    if(action.startsWith('export-')){downloadExport(action.slice(7));return;}
    if(action==='help')helpDialog();
    else if(action==='new'){if(confirm('Create an empty project? Your current project remains available through Undo.')){selected='';viewBox=null;mutate('Create empty project',p=>Object.assign(p,emptyProject()),{strict:false});}}
    else if(action==='demo'){selected='';viewBox=null;mutate('Load synthetic demonstration',p=>Object.assign(p,demoProject()),{strict:false});}
    else if(action==='import')importDialog();
    else if(action==='preview-import')await previewImport();
    else if(action==='apply-import'&&pendingImport){const importData=pendingImport;selected='';viewBox=null;if(mutate(`Import ${importData.type}`,p=>Object.assign(p,importData.candidate),{strict:false})){closeDialog();toast('Import applied. Review the reported findings before approval.');}}
    else if(action==='close-dialog')closeDialog();
    else if(action==='array')arrayDialog();
    else if(action==='create-array'){const data=Object.fromEntries(new FormData($('arrayForm')));for(const k of ['rows','columns','pitch','x','y'])data[k]=Number(data[k]);const ports=generateArray(data);if(mutate('Generate site array',p=>p.ports.push(...ports))){viewBox=null;closeDialog();render();}}
    else if(action==='apply-die'){const form=$('dieForm'),data=Object.fromEntries(new FormData(form));for(const k of ['x','y','width','height','rotation','edgeKeepout','cornerKeepout'])data[k]=Number(data[k]);data.mirrorX=Boolean(form.elements.mirrorX.checked);if(mutate(`Place die ${form.dataset.id}`,p=>Object.assign(p.dies.find(d=>d.id===form.dataset.id),data))){viewBox=null;closeDialog();render();}}
    else if(action==='advanced')advancedDialog();
    else if(action==='apply-json'){const parsed=importJSON($('projectJSON').value);if(mutate('Apply explicit project JSON edits',p=>Object.assign(p,parsed),{strict:false})){selected='';viewBox=null;closeDialog();render();}}
    else if(action==='undo'||action==='redo'){if(action==='undo')store.undo();else store.redo();if(!store.project.ports.some(n=>n.id===selected))selected='';render();persist();}
    else if(action==='fit'){viewBox=null;renderMap();}
    else if(action==='lock'&&selected)mutate(`Toggle site lock ${selected}`,p=>{const n=portAt(p,selected);n.locked=!n.locked;});
    else if(action==='disconnect'&&selected)mutate(`Disconnect ${selected}`,p=>disconnect(p,selected));
    else if(action==='optimize')optimize();
    else if(action==='cancel-optimize'){cancelWorker();render();toast('Optimization cancelled. No candidate was applied.');}
    else if(action==='previous-page'){tablePage--;renderConnectionRows();}
    else if(action==='next-page'){tablePage++;renderConnectionRows();}
    else if(action==='baseline-current'){baseline=clone(store.project);render();toast('Current revision captured as the review baseline for this session.');}
    else if(action==='baseline-import'){openDialog('Load comparison baseline','The current design will not be changed.',`<input id="baselineFile" type="file" accept=".json">`,`<button data-action="apply-baseline" class="primary">Load baseline</button>`);}
    else if(action==='apply-baseline'){const file=$('baselineFile').files[0];if(!file)throw new Error('Select a baseline JSON file.');baseline=importJSON(await file.text());closeDialog();render();}
  }catch(error){if($('dialog').open)$('dialogError').textContent=error.message;else toast(error.message,true);}
});
document.addEventListener('change',e=>{
  if(e.target.name==='fromStage')fromStage=e.target.value;
  if(e.target.name==='toStage')toStage=e.target.value;
  if(e.target.id==='snap')snapStep=Math.max(0,Number(e.target.value)||0);
  if(e.target.dataset.layer){const kind=e.target.dataset.layer;if(e.target.checked)layers=[...new Set([...layers,kind])];else layers=layers.filter(k=>k!==kind);viewBox=null;render();}
  if(e.target.id==='viewSelect'){view=e.target.value;viewBox=null;render();}
  if(e.target.id==='strictToggle'){strict=e.target.checked;render();if(!strict)toast('Draft mode enabled. Invalid assignments will be reported, not blocked.');}
  if(e.target.id==='labelToggle'){labels=e.target.checked;render();}
  if(e.target.id==='overlayToggle'){overlay=e.target.checked;render();}
  if(e.target.id==='issueFilter'){issueFilter=e.target.value;render();}
  if($('dialog').open&&e.target.closest('#dialog')&&pendingImport){pendingImport=null;if($('applyImport'))$('applyImport').disabled=true;}
});
document.addEventListener('input',e=>{if(e.target.closest('#dialog')&&pendingImport){pendingImport=null;if($('applyImport'))$('applyImport').disabled=true;}});
document.addEventListener('submit',e=>{
  const form=e.target;if(!form.dataset.form)return;e.preventDefault();const data=Object.fromEntries(new FormData(form));
  if(form.dataset.form==='port'){const id=selected;mutate(`Edit site ${id}`,p=>{const n=portAt(p,id);if(!n.locked){n.x=Number(data.x);n.y=Number(data.y);}for(const key of ['net','domain','role','label','pair','polarity'])n[key]=data[key];n.required=Boolean(form.elements.required.checked);});}
  if(form.dataset.form==='assign')assign(selected,data.target,Boolean(form.elements.replace.checked));
  if(form.dataset.form==='rules'){mutate('Update planning constraints',p=>{for(const key of Object.keys(ruleLabels))p.rules[key]=Number(data[key]);p.rules.terminalKind=data.terminalKind;p.rules.requirePowerForSignals=Boolean(form.elements.requirePowerForSignals.checked);p.rules.requireCompletePaths=Boolean(form.elements.requireCompletePaths.checked);},{strict:false});}
});
document.addEventListener('keydown',e=>{
  if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||$('dialog').open)return;
  if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(e.shiftKey)store.redo();else store.undo();render();persist();}
  else if(e.key.toLowerCase()==='f'&&tab==='plan'){viewBox=null;renderMap();}
  else if(e.key==='Enter'&&e.target.closest('[data-port]')){selectPort(e.target.closest('[data-port]').dataset.port);}
});
window.addEventListener('beforeunload',()=>cancelWorker());
render();persist();if(restoreError)toast(restoreError,true);
