import { normalizeProject, KINDS, worldPoint, indexProject } from './core/model.js';
import { escapeHTML } from './core/exporters.js';
import { INTEROP_VERSION, importKiCad, exportKiCad, verifyKiCadExport, objectDigest } from './core/terminal-interop.js';
import { verifyConnectivityContract, verifyIntentReview, previewMappingECO } from './core/connectivity-contract.js';
import { interoperabilityDemo, swappedInterfaceDemo } from './core/interop-demo.js';
const $=id=>document.getElementById(id),esc=escapeHTML,json=v=>JSON.stringify(v,null,2);
let {project,contract}=interoperabilityDemo(),review=null,pending=null,eco=null,previous=null,generated=null,timer,fileEpoch=0,contractEpoch=0;
const kinds=selected=>KINDS.map(k=>`<option ${k===selected?'selected':''}>${k}</option>`).join('');
$('interop').innerHTML=`<header><div class="logo" aria-hidden="true">${'<i></i>'.repeat(9)}</div><div><div class="brand">OpenBumpPlan</div><div class="tag">INTEROPERABILITY WORKBENCH · ${INTEROP_VERSION}</div></div><span class="spacer"></span><span class="local">● No design data leaves this device</span><a class="link" href="index.html">Planner ↗</a></header><main>
<section class="intro"><div><div class="eyebrow">From logical intent to a portable pin map</div><h1>Exchange files. Preserve meaning.</h1><p>Native KiCad terminals, independently supplied connectivity intent and checked mapping changes.</p></div><span class="spacer"></span><button id="demo">Load clean example</button></section>
<div class="banner">Engineering preview, not signoff. Imported tracks, vias, zones and stackup are <strong>not</strong> part of this terminal-map adapter. A passing intent review verifies logical mappings only. Example data and example intent are synthetic.</div>
<div class="grid"><div class="left"><section class="panel"><h3>01 / INPUT</h3><h2>Bring in a project or pin map</h2><label>Project JSON or KiCad board / footprint<input type="file" id="projectFile" accept=".json,.kicad_pcb,.kicad_mod"></label><div class="row"><button id="loadPlanner">Read planner's local project</button></div><div class="formgrid"><label>Native import site kind<select id="importKind">${kinds('pcb')}</select></label><label>Reference filter (optional)<input id="reference" placeholder="U1"></label></div><details><summary>Paste native KiCad text</summary><textarea id="nativeText" spellcheck="false" aria-label="KiCad input"></textarea><div class="row"><button id="previewImport">Preview native import</button></div></details><div id="importInfo" class="hint">No import pending. Nothing is replaced until you apply.</div><button id="applyImport" disabled>Apply previewed import</button></section>
<section class="panel"><h3>02 / INDEPENDENT INTENT</h3><h2>Check what must be connected</h2><label>Reviewed contract JSON<input id="contractFile" type="file" accept=".json"></label><label class="hint">Contract text (editable)<textarea id="contractText" spellcheck="false"></textarea></label><div class="row"><button id="check" class="primary">Check connectivity intent</button><button id="saveContract" class="quiet">Save contract</button></div><p class="hint">Use a separately reviewed specification. Generating a contract from the same mapping cannot reveal that mapping's mistakes.</p></section></div>
<div class="center"><section class="panel"><div class="row" style="margin-top:0"><h3 style="margin:0">LIVE PROJECT</h3><span class="spacer"></span><span id="reviewStatus" class="badge">Not reviewed</span></div><h2 id="projectName"></h2><div class="summary"><div><strong id="sites"></strong><span>Sites</span></div><div><strong id="links"></strong><span>Mappings</span></div><div><strong id="netCount"></strong><span>Intent nets</span></div></div><svg id="map" role="img" aria-label="Current logical terminal map"></svg><div class="row"><span class="small good">● die pad</span><span class="small">○ package / board terminal</span><span class="spacer"></span><button id="saveProject" class="quiet">Save project JSON</button></div><div class="digest" id="digest"></div><div id="findings" class="findings"></div><div class="row"><button id="saveReview" disabled>Export intent review</button><button id="replay" disabled>Independently replay</button></div><label class="hint">Verify a saved intent review against this project and the supplied contract<input id="reviewFile" type="file" accept=".json"></label></section>
<section class="panel"><h3>03 / MAPPING ECO</h3><h2>Preview changes before applying</h2><div class="row"><button id="swapDemo">Load swapped-map example</button><button id="undo" disabled>Undo applied change</button></div><label>Hash-bound mapping patch<textarea id="patchText" spellcheck="false" aria-label="Mapping ECO patch"></textarea></label><div class="row"><button id="previewEco">Check patch</button><button id="applyEco" class="primary" disabled>Apply checked patch</button></div><pre id="ecoInfo">No patch candidate. Locks, base identity, full intent coverage and planning rules are checked together.</pre></section></div>
<div class="right"><section class="panel"><h3>04 / NATIVE OUTPUT</h3><h2>Export a verified pin-map board</h2><div class="formgrid"><label>Selected layer<select id="exportKind">${kinds('ball')}</select></label><label>Output copper side<select id="side"><option>F.Cu</option><option>B.Cu</option></select></label><label>Round-pad diameter (µm)<input type="number" id="diameter" min=".001" step=".001" value="250"></label></div><p class="hint">Geometry is explicit: selected sites are flattened to package XY and emitted as circular pads. This is an unrouted starting board, not a full PCB conversion.</p><button id="makeExport" class="primary">Build & verify native output</button><pre id="exportInfo">No output generated.</pre><div class="row"><button id="saveBoard" disabled>.kicad_pcb</button><button id="saveFootprint" disabled>.kicad_mod</button><button id="saveReceipt" disabled>Receipt JSON</button></div><p class="hint">The board carries net assignments; the library footprint does not. Independent replay checks actual file terminals against the source project and your explicit export settings.</p></section>
<section class="panel"><h3>REVIEW BOUNDARIES</h3><h2>Three checks, different meanings</h2><p><strong>Import:</strong> coordinates, units, references and net identities are parsed; omitted content is reported.</p><p><strong>Intent:</strong> explicit graph connectivity is compared with a separate contract. Equal labels alone do not connect ports.</p><p><strong>Export:</strong> pin coordinates, nets, pad size and side are re-read and compared with the expected source and geometry.</p><p class="hint">No electrical, thermal, mechanical, manufacturing or regulatory approval is implied.</p></section></div></div></main><footer>Local-only • No cloud service, account, telemetry or external runtime dependencies • Save JSON to move between this workbench and the planner. Local storage is read only after an explicit request.</footer>`;
function notice(s,bad=false){$('notice').textContent=s;$('notice').className='show'+(bad?' bad':'');clearTimeout(timer);timer=setTimeout(()=>$('notice').className='',6500);}
function guarded(fn){return async()=>{try{await fn();}catch(e){notice(e.message,true);}};}
function invalidate(){review=null;eco=null;generated=null;$('applyEco').disabled=true;['saveBoard','saveFootprint','saveReceipt'].forEach(k=>$(k).disabled=true);$('exportInfo').textContent='No current verified output.';}
function setProject(p){fileEpoch++;contractEpoch++;project=normalizeProject(p);pending=null;$('applyImport').disabled=true;invalidate();render();}
function parseContract(){return JSON.parse($('contractText').value);}
function render(){
  $('projectName').textContent=project.name;$('sites').textContent=project.ports.length;$('links').textContent=project.connections.length;
  try{$('netCount').textContent=parseContract().nets.length;}catch{$('netCount').textContent='—';}
  $('digest').textContent='Current project SHA-256 · '+objectDigest(project);$('undo').disabled=!previous;
  $('reviewStatus').textContent=review?review.ok?(review.coverage==='all'?'All-port intent passes':'Listed-port intent passes'):`${review.issueCount} intent finding(s)`:'Not reviewed';
  $('reviewStatus').className='badge '+(review?(review.ok?'good':'bad'):'');
  $('saveReview').disabled=!review;$('replay').disabled=!review;
  $('findings').innerHTML=review?(review.ok?'<p class="good small">Current mappings match the supplied intent within the stated coverage. This is not electrical signoff.</p>':review.issues.map(i=>`<div class="finding"><b>${esc(i.code)}</b>${esc(i.message)}</div>`).join('')):'';
  const ctx=indexProject(project),points=project.ports.map(n=>({...n,...worldPoint(n,ctx)})),byId=new Map(points.map(n=>[n.id,n]));
  if(points.length){const xs=points.map(n=>n.x),ys=points.map(n=>-n.y),x0=Math.min(...xs),y0=Math.min(...ys),dx=Math.max(...xs)-x0,dy=Math.max(...ys)-y0,pad=Math.max(dx,dy,1)*.13,r=Math.max(dx,dy,1)*.012;
    $('map').setAttribute('viewBox',`${x0-pad} ${y0-pad} ${dx+2*pad} ${dy+2*pad}`);
    // Rendering is explicitly capped; the verification engines use all sites.
    $('map').innerHTML=project.connections.slice(0,3000).map(e=>{const a=byId.get(e.from),b=byId.get(e.to);return `<path d="M${a.x},${-a.y} L${b.x},${-b.y}" stroke="#365471" stroke-width="${r*.18}"/>`;}).join('')+points.slice(0,3000).map(n=>`<g><circle cx="${n.x}" cy="${-n.y}" r="${r}" fill="${n.kind==='pad'?'#6fdac5':'#15263a'}" stroke="#6fdac5" stroke-width="${r*.16}"/><text x="${n.x}" y="${-n.y-r*1.9}" font-size="${r*1.55}" fill="#c3d0e2" text-anchor="middle">${esc(n.label)}</text></g>`).join('');
    if(points.length>3000)$('findings').insertAdjacentHTML('beforeend','<p class="hint">Preview limited to 3,000 sites. All sites remain in the project and are checked/exported.</p>');
  }else $('map').innerHTML='';
}
function download(name,data){const blob=new Blob([typeof data==='string'?data:json(data)],{type:name.endsWith('.json')?'application/json':'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function readFile(input){const f=input.files[0];if(!f)throw new Error('Choose a file');if(f.size>5*1024*1024)throw new Error('File exceeds 5 MiB safety limit');return await f.text();}
function previewNative(text){const ref=$('reference').value.trim(),r=importKiCad(text,{kind:$('importKind').value,...(ref?{references:[ref]}:{})});pending=r;$('importInfo').textContent=`${r.report.terminalCount} terminals · ${r.report.footprints.join(', ')}\n${r.report.warnings.join('\n')}`;$('applyImport').disabled=false;}
function exportSpec(){return {kind:$('exportKind').value,side:$('side').value,diameter:Number($('diameter').value)};}
$('contractText').value=json(contract);
$('demo').onclick=guarded(()=>{const d=interoperabilityDemo();contract=d.contract;$('contractText').value=json(contract);previous=null;$('patchText').value='';setProject(d.project);});
$('projectFile').onchange=guarded(async()=>{pending=null;$('applyImport').disabled=true;const epoch=++fileEpoch;const text=await readFile($('projectFile'));if(epoch!==fileEpoch)return;if($('projectFile').files[0].name.endsWith('.json')){const p=normalizeProject(JSON.parse(text));pending={project:p};$('importInfo').textContent=`Preview: ${p.name}, ${p.ports.length} sites. Applying replaces only this workbench project.`;$('applyImport').disabled=false;}else previewNative(text);});
$('previewImport').onclick=guarded(()=>{pending=null;$('applyImport').disabled=true;previewNative($('nativeText').value);});
$('applyImport').onclick=guarded(()=>{if(!pending)throw new Error('No valid preview');previous=project;setProject(pending.project);notice('Preview applied. Prior review and exports invalidated.');});
$('loadPlanner').onclick=guarded(()=>{const s=localStorage.getItem('openbumpplan.project.v1');if(!s)throw new Error('No saved planner project on this origin. Load its exported JSON instead.');const p=normalizeProject(JSON.parse(s));pending={project:p};$('importInfo').textContent=`Preview local planner: ${p.name}, ${p.ports.length} sites`;$('applyImport').disabled=false;});
$('nativeText').oninput=()=>{fileEpoch++;pending=null;$('applyImport').disabled=true;};['reference','importKind'].forEach(k=>$(k).oninput=()=>{fileEpoch++;pending=null;$('applyImport').disabled=true;});
$('contractFile').onchange=guarded(async()=>{const epoch=++contractEpoch;invalidate();render();const text=await readFile($('contractFile'));if(epoch!==contractEpoch)return;$('contractText').value=text;render();});
$('contractText').oninput=()=>{contractEpoch++;invalidate();render();};
$('check').onclick=guarded(()=>{review=verifyConnectivityContract(project,parseContract());render();});
$('saveProject').onclick=()=>download('openbumpplan-project.json',project);
$('saveContract').onclick=guarded(()=>download('connectivity-contract.json',parseContract()));
$('saveReview').onclick=guarded(()=>{if(!review)throw new Error('No current review');download('connectivity-review.json',review);});
$('replay').onclick=guarded(()=>{const r=verifyIntentReview(project,parseContract(),review);notice(r.ok?'Review independently replayed against current project and supplied intent':'Review is stale, failing or does not match',!r.ok);});
$('reviewFile').onchange=guarded(async()=>{const r=verifyIntentReview(project,parseContract(),JSON.parse(await readFile($('reviewFile'))));notice(r.ok?'Saved review matches current project and supplied intent':'Saved review rejected: '+r.reason,!r.ok);});
$('swapDemo').onclick=guarded(()=>{const d=swappedInterfaceDemo();contract=d.contract;$('contractText').value=json(contract);previous=null;setProject(d.project);$('patchText').value=json(d.patch);review=verifyConnectivityContract(project,contract);render();});
$('patchText').oninput=()=>{eco=null;$('applyEco').disabled=true;};
$('previewEco').onclick=guarded(()=>{eco=null;$('applyEco').disabled=true;eco=previewMappingECO(project,JSON.parse($('patchText').value),parseContract());$('ecoInfo').textContent=`${eco.accepted?'Accepted candidate — not applied':'Rejected candidate'}\n${eco.changed} mapping edits · ${eco.planning.errors} planning errors · ${eco.intent.issueCount} intent findings\nCandidate SHA-256: ${eco.candidateProjectSHA256}`;$('applyEco').disabled=!eco.accepted;});
$('applyEco').onclick=guarded(()=>{const r=previewMappingECO(project,JSON.parse($('patchText').value),parseContract());if(!eco?.accepted||!r.accepted||r.candidateProjectSHA256!==eco.candidateProjectSHA256)throw new Error('Candidate no longer matches; preview again');previous=project;setProject(r.project);review=verifyConnectivityContract(project,parseContract());render();$('ecoInfo').textContent='Checked mapping change applied. Undo is available.';});
$('undo').onclick=guarded(()=>{if(!previous)throw new Error('Nothing to undo');const p=previous;previous=null;setProject(p);});
for(const k of ['exportKind','diameter','side'])$(k).oninput=()=>{generated=null;['saveBoard','saveFootprint','saveReceipt'].forEach(id=>$(id).disabled=true);$('exportInfo').textContent='Settings changed. Rebuild and verify.';};
$('makeExport').onclick=guarded(()=>{generated=null;['saveBoard','saveFootprint','saveReceipt'].forEach(id=>$(id).disabled=true);const options=exportSpec(),out=exportKiCad(project,options),r=verifyKiCadExport(project,out.board,out.receipt,options);if(!r.ok)throw new Error(r.issues.join('; '));generated=out;$('exportInfo').textContent=`${r.checked} terminals independently re-read and matched\n${out.receipt.warnings.join('\n\n')}\nBoard SHA-256: ${r.boardSHA256}`;['saveBoard','saveFootprint','saveReceipt'].forEach(k=>$(k).disabled=false);});
for(const [button,suffix,key]of [['saveBoard','kicad_pcb','board'],['saveFootprint','kicad_mod','footprint'],['saveReceipt','receipt.json','receipt']])$(button).onclick=guarded(()=>{if(!generated||!verifyKiCadExport(project,generated.board,generated.receipt,exportSpec()).ok)throw new Error('No current verified output');download('OpenBumpPlan_PinMap.'+suffix,generated[key]);});
render();
